### ISSUE TITLE
Error kicking off Shiny

### ISSUE THREAD

**Issue by ericaVoss** [emaprojects/EmaCovidFeasibility#2]
I'm getting the following error:

```
EmaCovidFeasibility:::launchEvidenceExplorer(dataFolder = file.path(getwd(),outputFolder,"shinyData"))

Warning in file(con, "r") :
  cannot open file 'md/about.md': No such file or directory
```

Commenting out this allowed me to run the Shiny:
https://github.com/emaprojects/EmaCovidFeasibility/blob/531389dfdd08521ceeeecb8a2bda5b6626db209b/inst/shiny/FeasExplore/app.R#L217

**Comment by hms1** [comment]
Hi and thanks for this!

It should be fixed in the latest commit - it looks like a few files had not previously been pushed to the repo (?)

Please let me know if it works and if I can close the issue :)

**Comment by hms1** [comment]
Please let me know if there are still issues and I'll re-open :)
